# Generated by Django 5.1 on 2024-08-14 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CURRICULUM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('option1', models.TextField(verbose_name='A')),
                ('option2', models.TextField(verbose_name='B')),
                ('option3', models.TextField(verbose_name='C')),
                ('option4', models.TextField(verbose_name='D')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Answer')),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('I', 'Intermediate'), ('H', 'Hard')], max_length=1)),
                ('question_for', models.CharField(choices=[('T', 'Test Exam'), ('M', 'Mid Exam'), ('F', 'Final Exam')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('T', 'Test Exam'), ('M', 'Mid Exam'), ('F', 'Final Exam')], default='T', max_length=1)),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_belongs_to', to='CURRICULUM.course')),
                ('lesson_topics', models.ManyToManyField(related_name='lesson_topics', to='CURRICULUM.lesson')),
                ('prerequisite_lessons', models.ManyToManyField(related_name='prerequest_for_exam', to='CURRICULUM.lesson')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EXAM.examduration')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('score', models.IntegerField()),
                ('percent', models.FloatField()),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result', to='CURRICULUM.lesson')),
            ],
        ),
    ]
