# Generated by Django 5.1 on 2024-08-14 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CURRICULUM', '0002_initial'),
        ('EXAM', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CURRICULUM.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXAM.question'),
        ),
    ]
