# Generated by Django 5.1 on 2024-08-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CurriculumApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('score', models.IntegerField()),
                ('percent', models.FloatField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('option1', models.TextField(verbose_name='A')),
                ('option2', models.TextField(verbose_name='B')),
                ('option3', models.TextField(verbose_name='C')),
                ('option4', models.TextField(verbose_name='D')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Answer')),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('I', 'Intermediate'), ('H', 'Hard')], max_length=1)),
                ('question_for', models.CharField(choices=[('M', 'Mid Exam'), ('F', 'Final Exam')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('M', 'Mid Exam'), ('F', 'Final Exam')], max_length=1)),
                ('date', models.DateTimeField()),
                ('starting_time', models.DateTimeField(auto_now_add=True)),
                ('ending_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_belongs_to', to='CurriculumApp.course')),
                ('lesson_topics', models.ManyToManyField(related_name='lesson_topics', to='CurriculumApp.lesson')),
                ('prerequisite_lessons', models.ManyToManyField(related_name='prerequest_for_exam', to='CurriculumApp.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('date_attempted', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.exam')),
            ],
        ),
    ]
