# Generated by Django 5.1 on 2024-08-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='logo/')),
                ('student_photo', models.FileField(upload_to='student_photo/')),
            ],
        ),
    ]
