# Generated by Django 5.1 on 2024-08-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True, verbose_name='Question')),
                ('option1', models.CharField(max_length=255, verbose_name='A')),
                ('option2', models.CharField(max_length=255, verbose_name='B')),
                ('option3', models.CharField(max_length=255, verbose_name='C')),
                ('option4', models.CharField(max_length=255, verbose_name='D')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=255, verbose_name='Answer')),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('score', models.IntegerField()),
                ('percent', models.FloatField()),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
