# Generated by Django 5.1 on 2024-08-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CURRICULUM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, unique=True, verbose_name='Question')),
                ('option1', models.CharField(max_length=300, verbose_name='A')),
                ('option2', models.CharField(max_length=300, verbose_name='B')),
                ('option3', models.CharField(max_length=300, verbose_name='C')),
                ('option4', models.CharField(max_length=300, verbose_name='D')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=300, verbose_name='Answer')),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CURRICULUM.lesson')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QUIZ.quiz_question')),
            ],
        ),
    ]
