# Generated by Django 5.1 on 2024-08-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('P', 'P'), ('C', 'C'), ('F', 'F')], default='P', max_length=1)),
            ],
        ),
    ]
