# Generated by Django 5.1 on 2024-08-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CurriculumApp', '0002_initial'),
        ('PaymentApp', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='approved_payment', to='User.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_payment', to='User.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='unit_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CurriculumApp.curriculum'),
        ),
    ]
