# Generated by Django 5.1 on 2024-08-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssignmentApp', '0002_initial'),
        ('CurriculumApp', '0001_initial'),
        ('ExamApp', '0001_initial'),
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('Finalexam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalexam_result', to='ExamApp.examresult')),
                ('Lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_result', to='CurriculumApp.lab')),
                ('Midexam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midexam_result', to='ExamApp.examresult')),
                ('assignment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_result', to='AssignmentApp.assignmentresult')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_name', to='CurriculumApp.curriculum')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_result', to='QuizApp.quizresult')),
            ],
        ),
    ]
