# Generated by Django 5.1 on 2024-08-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssignmentApp', '0002_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_creator', to='User.user'),
        ),
        migrations.AddField(
            model_name='assignmentresult',
            name='instructor',
            field=models.OneToOneField(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ResultCreator', to='User.user'),
        ),
        migrations.AddField(
            model_name='assignmentresult',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='ResultOwner', to='User.user'),
        ),
        migrations.AddField(
            model_name='studentassignmentsubmit',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='AssignmentApp.assignment'),
        ),
        migrations.AddField(
            model_name='studentassignmentsubmit',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_submitted', to='User.user', verbose_name='Students'),
        ),
    ]
