# Generated by Django 5.1 on 2024-08-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BlogPostApp', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_1',
            field=models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='User.user'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_2',
            field=models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='User.user'),
        ),
        migrations.AddField(
            model_name='questionary',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionaries', to='BlogPostApp.blogpost'),
        ),
        migrations.AddField(
            model_name='response',
            name='questionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='BlogPostApp.questionary'),
        ),
    ]
