# Generated by Django 5.1 on 2024-08-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CurriculumApp', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_cart', to='User.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='course_instructor', to='User.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, related_name='next_courses', to='CurriculumApp.course'),
        ),
        migrations.AddField(
            model_name='cart',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_in_cart', to='CurriculumApp.course'),
        ),
        migrations.AddField(
            model_name='additionalnote',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_additional_notes', to='CurriculumApp.course'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='courses',
            field=models.ManyToManyField(to='CurriculumApp.course'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, related_name='next_courses', to='CurriculumApp.curriculum'),
        ),
        migrations.AddField(
            model_name='cart',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_in_cart', to='CurriculumApp.curriculum'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CurriculumApp.curriculum'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollment_history', to='User.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_course', to='CurriculumApp.course'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CurriculumApp.curriculum'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Instructor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_Instructor', to='User.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='StudentFeedback', to='User.user'),
        ),
        migrations.AddField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CurriculumApp.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CurriculumApp.course'),
        ),
    ]
