# Generated by Django 5.1 on 2024-08-17 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumApp', '0003_rename_added_date_cart_created_at_remove_cart_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_length',
        ),
        migrations.CreateModel(
            name='Lesson_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='video/')),
                ('video_length', models.CharField(max_length=100)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_videos', to='CurriculumApp.lesson')),
            ],
        ),
    ]
