# Generated by Django 5.1 on 2024-08-14 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ASSIGNMENT', '0002_initial'),
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to='USER.instructor'),
        ),
        migrations.AddField(
            model_name='studentassignmentsubmit',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='ASSIGNMENT.assignment'),
        ),
        migrations.AddField(
            model_name='studentassignmentsubmit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_submitted', to='USER.student'),
        ),
    ]
